<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_signInPassword</name>
   <tag></tag>
   <elementGuidId>773d4c38-5423-45b4-80e0-558786e0a9f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signInPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d612d319-acb2-4389-b7c7-5ba67218bcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>240689a1-169d-4278-b1b2-3c44c59d2fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>e871cf4b-d473-433c-bae7-6627516995f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signInPassword</value>
      <webElementGuid>419a0b32-efc3-4661-88ee-4b39ced567c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInPassword</value>
      <webElementGuid>359bfc58-4a04-417c-9ead-fba0a5b7f8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value> Password</value>
      <webElementGuid>fa7a141b-ec0b-4ff9-866c-ae888ad9f16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e9b29b8a-7c17-4dfb-bc9c-c332ca4c5825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInPassword&quot;)</value>
      <webElementGuid>991638be-2d0c-4c80-b213-be0ccfca4b9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signInPassword']</value>
      <webElementGuid>661ca250-6f7e-4135-90b8-4bedadb969fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[2]/div/div/input</value>
      <webElementGuid>e3f84012-70b7-4c14-a662-1d7efdb5e9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>3eb0a162-04e7-4721-bcf8-ebc1f01388e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'signInPassword' and @id = 'signInPassword']</value>
      <webElementGuid>1bc15d17-2f15-4964-8c9b-184f1e29da02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
