<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_xahtuk44gmail.com</name>
   <tag></tag>
   <elementGuidId>d9c57b48-8112-458a-9da6-e9effb5d71e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.Sailor-Email-Address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/div/div/div[2]/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>df025ed7-8814-46f9-9dee-91f614eaef49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Sailor-Email-Address</value>
      <webElementGuid>c5384739-4a17-4d59-aff6-e721f0c653f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>xahtuk44@gmail.com</value>
      <webElementGuid>8cb3a838-0ecc-43a8-84b0-93c9f84a4b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;Accounts Dashboard&quot;]/div[@class=&quot;Accounts__body&quot;]/div[@class=&quot;Accounts__content&quot;]/div[@class=&quot;Accounts__bodySection&quot;]/div[@class=&quot;Card -largeIcon profile-image&quot;]/div[@class=&quot;Card__content null&quot;]/p[@class=&quot;Sailor-Email-Address&quot;]</value>
      <webElementGuid>71ab633a-63ac-4652-91e3-8bca9490bb5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div[2]/p[2]</value>
      <webElementGuid>154e538f-ea66-45d5-8102-05a141e202b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AHOY SAILOR!'])[1]/following::p[3]</value>
      <webElementGuid>d92a6e5b-f12d-49e8-99ae-d673c548a26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Ships'])[1]/following::p[3]</value>
      <webElementGuid>8b6494b3-784b-4151-b842-969b3596bf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::p[1]</value>
      <webElementGuid>f9b0ce5e-293d-4450-9526-50d1b7f52acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upcoming Voyages'])[1]/preceding::p[1]</value>
      <webElementGuid>3bb1cf0d-8b35-459d-b70f-6e6c46387f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='xahtuk44@gmail.com']/parent::*</value>
      <webElementGuid>81305968-06b6-4a88-916c-148f0568ab7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>21e4ec64-d3bd-42a4-81bb-9e1909df71c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'xahtuk44@gmail.com' or . = 'xahtuk44@gmail.com')]</value>
      <webElementGuid>9deb1ad8-689d-44aa-91fe-a9323bee1440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
