<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nov</name>
   <tag></tag>
   <elementGuidId>818d475c-8de6-44e9-b4f3-84d0f20adc1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e47a590-0a1e-4c4e-bf7f-6f325d6774cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DatePicker__month -inRange -hover -startHover</value>
      <webElementGuid>3b8f47ce-dcb1-4cfa-a23f-40e50341a0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a7eaa064-4b96-4fa9-a47f-32462149dc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>42ceb47f-4048-450f-a27f-d59cfed8637e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nov</value>
      <webElementGuid>2eaefba5-e93f-42e2-987b-1333f382f590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;10&quot;)</value>
      <webElementGuid>26c31e11-7c99-4511-9bd3-6c46b01a4f76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='10']</value>
      <webElementGuid>ba9c208c-018d-4ebe-b3f0-99746731352c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopoverTravelDates']/div[2]/div/div/div[3]/button[11]</value>
      <webElementGuid>fd3dad08-e3f2-4041-b891-c6e63993be05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oct'])[1]/following::button[1]</value>
      <webElementGuid>b5791297-7cd8-49af-989b-f0a599a271c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sep'])[1]/following::button[2]</value>
      <webElementGuid>71e76a13-be23-4116-a68f-93ec35a244d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dec'])[1]/preceding::button[1]</value>
      <webElementGuid>429b14a6-21d7-4293-9524-dd351ad95f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[11]</value>
      <webElementGuid>e1d16e7a-ba18-4dca-8057-4f1f49c18b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = '10' and @type = 'button' and (text() = 'Nov' or . = 'Nov')]</value>
      <webElementGuid>1f7a40f2-d101-4fed-9d7d-adf349f996c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
